### ISSUE TITLE
'Share With Team' option is not displayed after sharing and then making a template private.

### ISSUE THREAD

**Issue by diclee** [koding/koding#10035]
## Current Behavior
It's displayed again after reloading the page.
![gif](http://g.recordit.co/mWA8gmyHnT.gif)
http://recordit.co/mWA8gmyHnT

**Comment by diclee** [comment]
@hakankaradis when member shared and unshared a stack template, also 'Edit' becomes 'View Stack' and 'Clone' disappears from the menu until reloading the page.
![gif](http://g.recordit.co/uhStS3ivCU.gif)
http://recordit.co/uhStS3ivCU

**Comment by hakankaradis** [comment]
@diclee 
I believe these bugs has been fixed with https://github.com/koding/koding/pull/10195
Here are the screencasts
Member share and unshare her private stack: http://recordit.co/YMVEP24DG1
Admin share and unshare her private stack: http://recordit.co/fIA4uiYNCT
Can you please check them after #10195 is merged?

**Comment by diclee** [comment]
Verify passed on latest.
