### ISSUE TITLE
Shared stack template is added to other member's sidebar directly and removed after reloading.

### ISSUE THREAD

**Issue by diclee** [koding/koding#10204]
## Current Behavior
![gif](http://g.recordit.co/aZoMDsMCRP.gif)
http://recordit.co/aZoMDsMCRP

It shouldn't be added to the sidebar in the first place or shouldn't be removed after reloading.

**Comment by hakankaradis** [comment]
@diclee You are right, the shared stack template shouldn't be added to sidebar for member because the only actions that user can do are viewing and/or cloning the stack template.

But when the owner of the shared stack template refresh the page, it will also disappeared from sidebar because we don't want to show the drafts on sidebar thats why it is removed from sidebar.
We may do exception only for shared stack template? We can show them on the sidebar? Wdyt @gokmen

**Comment by diclee** [comment]
Verify passed on sandbox.
