### ISSUE TITLE
Payment history shows same transaction as multiplied.

### ISSUE THREAD

**Issue by diclee** [koding/koding#10210]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/21655206/e5520b26-d26d-11e6-98e0-10ada06ada41.png)

**Comment by usirin** [comment]
@cihangir I am guessing these are due to the changes in the plans, what is the easiest way for me to filter out all those details? Or maybe we shouldn't filter at all and show a description of what those charges are? 

I am leaning towards "filtering and not showing at all" option, as it's mostly a implementation detail; but since this is a delicate information for the end user, I can't say we should do this 100%. 

/cc @devrim @sinan

**Comment by cihangir** [comment]
The bug shown in the image must be a pagination bug, with the current structure we should only show one 0$  per month ( while changing the subs on the fly ).

Second, for filtering, i agree with you. If we remove the invoices that have `"paid": false` we should be good. Stripe API does not have filtering on that field, we need to do that on client side. https://stripe.com/docs/api#list_invoices

**Comment by diclee** [comment]
This issue is not reproducible anymore. Closing for now.
