### ISSUE TITLE
Time-out error shouldn't be displayed for stack builds that really need longer times than normal builds.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8647]
If a user clicks on 'Try Building Again' while the process is still continuing without a problem, that will ruins the process.
We should ping the machine if the build process still continues or something is really broken.

cc/ @gokmen for further details.

![image](https://cloud.githubusercontent.com/assets/8261892/17233402/68b8d4a2-54e4-11e6-973b-c878f860fe7c.png)
note: the above screenshot is from the design document taken in order to give an idea about the modal appearing.
##

**Comment by gokmen** [comment]
@alex-ionochkin for some stack templates this process may take an hour to finalize and with those builds I'm seeing `try building again` which is not correct and may cause to corrupt stack build process. Instead we need to make this based on the connection status, we can try to send `ping` to kite and based on the response we can decide to show that state, and maybe instead of `try building again` we can show `reload page` button instead.

**Comment by diclee** [comment]
Verify passed on latest.
