### ISSUE TITLE
klientctl: rework ls method

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#9305]
Currently `kd ls` uses kontrol as a machine list backend. This is responsible for incomplete/inaccurate output from the command.

Known bugs:

1) when a machine is turned off (by default all machines are turned off after 1h) it's not listed by `kd ls` and it should be
2) building a stack is a two-step process: 2a) install a klient (kloud responsibility) 2b) execute user script (user resposibility); if building a stack fails at step 2b), `kd ls` lists such machine either way, since klient was installed and registered to kontrol successfully - and it shouldn't list it
## Expected Behavior

`kd ls` should return accurate list of available machines (either on-line or off-line).

Bonus point - if stack is being build the jMachine.status.state for each machine should be set to Building and `kd ls` should report such machine as such (`deploying`, `building` - in progress). To have the status for each machine even more accurate.
## Current Behavior

`kd ls` does not return accurate machine list - `kd ls --all` was introduced to list machines, that are missing due to bug 1), but solution suffers from bug 2).
## Possible Solution

Add `machine.list` method to kloud and use it as a backend instead of kontrol.

/cc @cihangir @devrim

**Comment by ppknap** [comment]
`kd machine mount` needs additional changes in this command. Current status:
- [x] add back-end to `kd machine list` in kloud (done in #9485)
- [x] implement new logic in `klientctl` which uses implemented back-end (done in #9485)
- [ ] get machine IDs which will be used as unique keys in klient - needed to bind mounts with machine
- [ ] rework aliases since `klient` generates them based on kite responses from `kontrol` which is not compatible with new logic - add them to `kd machine list`
- [ ] replace depricated `kd list/ls` with new implementation
- [ ] add `--json` flag which is meant to be provided across all `kd` commands.

**Comment by cihangir** [comment]
@ppknap could you also make sure kd stops working for teams that are in due payment state ASAP?

**Comment by ppknap** [comment]
@cihangir yes, this will be done as a separate issue (#8955). These changes are also made to bypass kontrol dependency (at this moment `kd list` uses it). We will probably need to create payment backend in `kloud` and then integrate it with `kd`. We should discuss this together with @rjeczalik once `kd machine list/mount` are completed because I'm not sure if we should block all or only specific commands. In my opinion existing mounts and cmds like `kd machine ssh` should work even if the user is blocked due to missing payment.

**Comment by rjeczalik** [comment]
> In my opinion existing mounts and cmds like kd machine ssh should work even if the user is blocked due to missing payment.

All existing mounts should be forcefully unmounted and `kd ssh` should not also work (I mean mostly the `klient.addSshKey` and alike, we won't block direct uses of `ssh`). Basically all kd commands that interact with Koding should stop working.

@cihangir Am I correct?

**Comment by cihangir** [comment]
@rjeczalik you are correct sir!

**Comment by ppknap** [comment]
This is done by #9485
