### ISSUE TITLE
Rework `kd mount` method.

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#9306]
Currently `kd mount` can sometimes lose the remote mount (fuse) or not sync the files fully (rsync).
## Expected Behavior

Ensure it's working, especially it:
- reconnects successfully (turning on/off wifi, changing network, turning vpn on/off, klient restart)
- does not stale nor goes out of sync (one-way sync - rsync - does not overwrite files, when they were edited on a remote end but not yet fetch/synced locally)

Additionally we should require that a machine is `alwaysOn` before attempting to mount - or even better - ensure that klient's `usage` kite metchod, which is used by kloud to query the idle time, is taking mounts into account and does not allow for turning off a machine if it has active mounts. This is responsible for majority of "broken" mounts.

Similarly to https://github.com/koding/koding/issues/9252 we should allow for remote configuration of the machine - toggling `alwaysOn`, managing shared users etc.
## Current Behavior

`kd mount` sometimes fail.
## Possible Solution

It should not.

/cc @cihangir @devrim

**Comment by ppknap** [comment]
In order to implement `kd machine mount` additional steps are needed:
- [ ] improve `kite*pingers` which currently try to monitor non existing machines. They are used as health checkers for mounted machines.
- [ ] rework `rsync`process runner which currently tries to fetch files even when machine is unavailable.
- [ ] rework `mount` logic which tries to create new mount when machine address has changed. This will be resolved by machine IDs taken from `kloud`.

**Comment by ppknap** [comment]
Done by: #10531
