### ISSUE TITLE
'original stack template has been updated' notification appears for the user that cloned also when he makes the changes himself.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9972]
## Current Behavior
Only the clone stack template is changed, the original stack template is not changed in below example.
![gif](http://g.recordit.co/H0D7fLq2Jm.gif)
http://recordit.co/H0D7fLq2Jm

**Comment by hakankaradis** [comment]
@diclee 
I think it is kind of expected behaviour. 
When you came to stack-editor page, it checks that the current stack template is clone of one of the shared stack template and if so, it compares its content with original stack template and if there is difference, the warning view is appeared.

I think having warning view is expected but copy is wrong. Because it say the original stack template has been updated, I think it should say `This stack template is different than original one` or something. I believe it will make more sense? 
@gokmen can you please share your thought for this bug please?

**Comment by gokmen** [comment]
@hakankaradis this warning should only be visible if original content has changed not the cloned content.

**Comment by diclee** [comment]
Verify passed on latest.
